match x:
    case f"x": ...
    case f"{y}": ...
    case "implicitly " f"concatenated": ...
    case t"x": ...
    case t"{y}": ...
    case t"implicitly " t"concatenated": ...
    case "x" | f"x": ...
    case f"x" as y: ...
    case ["x", f"x", *rest]: ...
    case "x", t"x": ...
    case Point("x", f"x", y=t"x"): ...
    case {"x": f"x", **rest}: ...
