match x:
    case "x": ...
    case b"x": ...
    case r"x" u"x": ...
    case "implicitly " "concatenated": ...
    case b"implicitly " b"concatenated": ...
    case ["x", b"x", "a" "b"]: ...
    case {"x": _, b"x": _, "a" "b": _}: ...
    case Point("x", y=b"x" b"y"): ...
